# Generated by Django 4.2.1 on 2023-05-23 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('quality', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('delivery', models.DateField()),
                ('credibility', models.CharField(max_length=20)),
                ('license', models.BooleanField()),
                ('distance', models.DecimalField(decimal_places=4, max_digits=10)),
                ('shipping_fees', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('location', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Weights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criteria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SupplierApp.criteria', verbose_name='criteria')),
            ],
        ),
        migrations.AddField(
            model_name='criteria',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SupplierApp.supplier', verbose_name='supplier'),
        ),
        migrations.CreateModel(
            name='BenefitCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', models.TextField()),
                ('cost', models.TextField()),
                ('criteria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SupplierApp.criteria', verbose_name='criteria')),
            ],
        ),
        migrations.CreateModel(
            name='AHPcalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ranking', models.IntegerField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SupplierApp.supplier', verbose_name='supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
