# Generated by Django 4.2.1 on 2023-06-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=150)),
                ('results', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ranking', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('financial_status', models.IntegerField()),
                ('quality', models.IntegerField()),
                ('service', models.IntegerField()),
                ('reputation', models.IntegerField()),
                ('technical_capability', models.IntegerField()),
                ('price_cost', models.IntegerField()),
            ],
        ),
    ]
