# Generated by Django 4.2.1 on 2023-06-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SupplierApp', '0002_alter_ranking_supplier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='supplier_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
