# Generated by Django 4.2.1 on 2023-05-16 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(max_length=20)),
                ('price', models.IntegerField()),
                ('delivery_time', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('distance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('location', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Weights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criteria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SupplierManagementApp.criteria', verbose_name='criteria')),
            ],
        ),
        migrations.CreateModel(
            name='BenefitCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', models.TextField()),
                ('cost', models.TextField()),
                ('criteria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SupplierManagementApp.criteria', verbose_name='criteria')),
            ],
        ),
        migrations.CreateModel(
            name='AHPcalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ranking', models.IntegerField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SupplierManagementApp.supplier', verbose_name='supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
